//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int ID { get; set; }
        public int ID_Bill { get; set; }
        public int ID_Product { get; set; }
        public Nullable<int> SumCount { get; set; }
        public Nullable<long> SumPrice { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
    }
}
